on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          artifacts: 'theme_ai_center.zip'
          draft: true
          prerelease: true
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with: 
          type: 'zip'
          filename: 'theme_ai_center.zip'
          exclusions: '*.git* JasonTheme/ _theme_info.txt Makefile README.md'  
