on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zip
        run: sudo apt-get install zip

      - name: Create Zip
        run: |
          cd .. ; 
          zip -r theme_ai_center.zip wp_theme_ai_epfl.ch/ \
              --exclude "wp_theme_ai_epfl.ch/*.git*" \
              --exclude "wp_theme_ai_epfl.ch/JasonsTheme/*" \
              --exclude "wp_theme_ai_epfl.ch/_theme_info.txt" \
              --exclude "wp_theme_ai_epfl.ch/Makefile" \
              --exclude "wp_theme_ai_epfl.ch/README.md" ;
          cp theme_ai_center.zip theme_ai_center_${{ github.ref_name }}.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: | 
            ../theme_ai_center_${{ github.ref_name }}.zip 
            ../theme_ai_center.zip
          generate_release_notes: true