name: Releases

on: 
  push:
    tags:
    - 'release'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
    - name: "theme_ai_center"