on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zip
        run: sudo apt-get install zip

      - name: Create Zip
        run: zip -r theme_ai_center.zip . -x '*.git* JasonTheme/ _theme_info.txt Makefile README.md'

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: true
          prerelease: true
          files: theme_ai_center.zip