on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zip
        run: sudo apt-get install zip

      - name: Create Zip
        run: |
          mkdir -p dist/theme_ai_center
          mv assets blocks parts patterns templates README.md *.php *.css theme.json dist/theme_ai_center
          cd dist
          zip -r theme_ai_center.zip theme_ai_center
          cp theme_ai_center.zip theme_ai_center_${{ github.ref_name }}.zip
          pwd
          ls -al

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: | 
            ./dist/theme_ai_center_${{ github.ref_name }}.zip 
            ./dist/theme_ai_center.zip
          generate_release_notes: true